name: Deploy Bundle to Dev

on:
  push:
    branches: [master]

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::914054469264:role/github-actions-admin-dev
          aws-region: us-east-2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::914054469264:role/terraform-admin
          aws-region: us-east-2
          role-chaining: true

      - name: Terraform init
        id: init
        run: terraform init -backend-config=dev.tfbackend
        working-directory: terraform/
        continue-on-error: false

      - name: Terraform apply dev
        id: plan
        run: terraform apply -auto-approve
        working-directory: terraform/
        continue-on-error: false
        env:
          TF_VAR_env: dev
          TF_VAR_r2_access_key: ${{secrets.R2_ACCESS_KEY}}
          TF_VAR_r2_secret_key: ${{secrets.R2_SECRET_KEY}}

  build-release:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
      actions: read
    strategy:
      matrix:
        node: ['20.x']
        os: [ubuntu-latest]
    env:
      CI: 1
      HUSKY: 0 # disables husky hooks
      NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
    needs:
      -  terraform-dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Configure AWS Actions Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::914054469264:role/github-actions-admin-dev
          aws-region: us-east-2

      - name: Configure AWS Terraform Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::914054469264:role/terraform-admin
          aws-region: us-east-2
          role-chaining: true

      - name: Start Deploy Message
        uses: Basis-Theory/github-actions/deploy-slack-action@master
        with:
          slack-api-token: ${{ secrets.SLACK_DUCKBOT_API_KEY }}
          channel: ${{ vars.SLACK_DUCKBOT_PRODUCT_DEPLOY_CHANNEL }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --no-progress --ignore-scripts

      - name: Get Next Version
        run: make get-version

      - name: Build
        run: make build
        env:
          SKIP_INSTALL: 1 # install with cache was done already

      - name: Deploy CDN Bundle to Dev
        run: make upload-bundle
        env:
          AWS: true
          BLOB: true
          CLOUDFLARE: true
          ENVIRONMENT: dev
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          IS_PR_WORKFLOW: true

  tag-and-release:
    runs-on: ubuntu-latest
    needs:
      - build-release
      - terraform-dev
    strategy:
      matrix:
        node: [ '20.x' ]
    steps:
      - name: Version and Tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release Notes
        id: release_notes
        uses: actions/github-script@v6
        env:
          NEW_RELEASE_TAG: ${{ steps.bump_version.outputs.new_tag }}
        with:
          result-encoding: string
          script: |
            const { NEW_RELEASE_TAG } = process.env;
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const releaseNotes = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: NEW_RELEASE_TAG,
              previous_tag_name: latestRelease.data.tag_name,
            });
            return releaseNotes.data.body;

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: false
          body: ${{ steps.release_notes.outputs.result }}
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
