name: Pull Request

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
      actions: read
    strategy:
      matrix:
        node: [ '20.x' ]
        os: [ ubuntu-latest ]
    env:
      HUSKY: 0 # disables husky hooks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS Actions Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::914054469264:role/github-actions-admin-dev
          aws-region: us-east-2

      - name: Configure AWS Terraform Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::914054469264:role/terraform-admin
          aws-region: us-east-2
          role-chaining: true

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - id: read-package-json
        name: Read package.json
        run: |
          content=`cat package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"got

      - name: Verify
        run: make verify
        env:
          SKIP_INSTALL: 1 # install with cache was done already

      - name: Upload CDN Bundle Blob
        run: make upload-bundle
        env:
          ENVIRONMENT: dev
          IS_PR_WORKFLOW: true
